on: 
  push: 
    branches: [master]

jobs:
  veracode-auto-package:
    name: Veracode Auto Package
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Veracode CLI Download and Package
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output veracode-auto-pack-dvsa-python.zip --trust
          ls -l
          
      - name: Check if veracode_pack exists
        run: |
          if [ -f /home/runner/work/autopackage_python/autopackage_python/veracode-auto-pack-dvsa-python.zip/veracode-auto-pack-autopackage_python-python.zip ]; then
            echo "Arquivo encontrado: veracode-auto-pack-autopackage_python-python.zip"
          else
            echo "Arquivo não encontrado!"
            exit 1  # Termina o processo com erro se o arquivo não for encontrado
          fi



      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: veracode_pack
          path: veracode-auto-pack-dvsa-python.zip

  Veracode-SAST-Pipeline:
    name: Veracode SAST Pipeline
    runs-on: ubuntu-latest
    needs: [veracode-auto-package]

    steps:
      - name: Download artfacts
        uses: actions/download-artifact@v3
        with:
          name: veracode_pack
          path: ./veracode_auto_pack

      - name: Check file permissions
        run: |
         ls -l ./veracode_auto_pack
         chmod +r ./veracode_auto_pack/veracode-auto-pack-autopackage_python-python.zip  # Ajuste para o arquivo correto
         ls -l ./veracode_auto_pack/veracode-auto-pack-autopackage_python-python.zip  # Verifique se o arquivo tem permissão de leitura
      
      - name: Pipeline Scan with wrapper
        run: |
          curl -O -L https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -u pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar -vid "${{ secrets.VERACODE_ID }}" -vkey "${{ secrets.VERACODE_KEY }}" --file ./veracode_auto_pack/veracode-auto-pack-autopackage_python-python.zip
        continue-on-error: false
