on: 
  push: 
    branches: [master]

jobs:
  veracode-auto-package:
    name: Veracode Auto Package
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Veracode CLI Download and Package
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output verascan --trust
          ls -l
          
      - name: Check if verascan exists
        run: |
          if [ -f /home/runner/work/autopackage_python/autopackage_python/verascan/verascan.zip ]; then
           echo "Arquivo encontrado: verascan.zip"
          else
           echo "Arquivo não encontrado!"
           exit 1  # Termina o processo com erro se o arquivo não for encontrado
          fi




      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: veracode_pack
          path: verascan

  Veracode-SAST-Pipeline:
    name: Veracode SAST Pipeline
    runs-on: ubuntu-latest
    needs: [veracode-auto-package]

    steps:
      - name: Download artfacts
        uses: actions/download-artifact@v4
        with:
          name: veracode_pack
          path: ./veracode_auto_pack
      
      - name: Pipeline Scan with wrapper
        run: |
          curl -O -L https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -u pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar -vid "${{ secrets.VERACODE_ID }}" -vkey "${{ secrets.VERACODE_KEY }}" --file ./veracode_auto_pack/veracode-auto-pack-autopackage_python-python.zip
        continue-on-error: false


  Install-Requeriments:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.0b1-buster
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: install requeriments
      run: |
        python -m pip install --no-cache-dir pip==22.0.4
        
  Veracode_Software_Composition_Analisys:
    runs-on: ubuntu-latest
    needs: [Install-Requeriments]
    container:
       image: python:3.11.0b1-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pip install
        run: |
          python -m pip install --no-cache-dir pip==22.0.4

      - name: Listing
        run: |
          ls -lah

        
      - name: Run SCA Scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
          export SRCCLR_SCM_URI="https://github.com/lucasferreiram3/PyGoat.git"
          export SRCCLR_SCM_REF=${{ github.workflow }}
          export SRCCLR_SCM_REF_TYPE="branch"
          export SRCCLR_SCM_REV=${{ github.run_id }}
          export EXTRA_ARGS='--update-advisor --uri-as-name'
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan --update-advisor --uri-as-name

  Veracode-SAST-Policy-Scan:
     name: Veracode Policy Scan
     runs-on: ubuntu-latest
     needs: [veracode-auto-package]

     steps:
       - name: Download artfacts
         uses: actions/download-artifact@v4
         with:
           name: veracode_pack
           path: ./veracode_auto_pack

       - name: Upload and Scan - Action
         uses: veracode/veracode-uploadandscan-action@0.2.7
         with:
           appname: App-Package-Python
           filepath: ./veracode_auto_pack/veracode-auto-pack-autopackage_python-python.zip
           vid: "${{ secrets.VERACODE_ID }}"
           vkey: "${{ secrets.VERACODE_KEY }}"
           createProfile: true
           deleteincompletescan: 2

  Veracode-SAST-SandBoxScan:
     name: Veracode SandBox Scan
     runs-on: ubuntu-latest
     needs: [veracode-auto-package]

     steps:
       - name: Download artfacts
         uses: actions/download-artifact@v3
         with:
           name: veracode_pack
           path: ./veracode_auto_pack

       - name: Upload and Scan - Action
         uses: veracode/veracode-uploadandscan-action@0.2.7
         with:
           appname: App-Package-Python
           filepath: ./veracode_auto_pack/veracode-auto-pack-autopackage_python-python.zip
           sandboxName: master
           createSandBox: true
           vid: "${{ secrets.VERACODE_ID }}"
           vkey: "${{ secrets.VERACODE_KEY }}"
           createProfile: true
           deleteincompletescan: 2
