on: 
  push: 
    branches: [master]

jobs:
  veracode-auto-package:
    name: Veracode Auto Package
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Veracode CLI Download and Package
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output veracode-auto-pack-Web-dotnet-js.zip --trust
          ls -l

      - name: Upload artfacts
        uses: actions/upload-artifact@v4
        with:
          name: artfacts
          path: ${{env.package_path}}/${{env.package_name}}

      - name: Pipeline Scan with wrapper - default policy
        env:
          POLICY_NAME: Veracode Recommended Medium
        run: |
          curl -O -L https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -u pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar -vid "${{ secrets.VERACODE_ID }}" -vkey "${{ secrets.VERACODE_KEY }}" --file "./${{env.package_path}}/${{env.package_name}}" -pn "${{ env.POLICY_NAME }}" --issue_details true --json_output true
        continue-on-error: true

  Veracode-Policy-Scan:
    name: Veracode Policy Scan
    runs-on: ubuntu-latest
    needs: [veracode-auto-package]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artfacts
          path: ./${{env.package_path}}

      # Usando apenas o wrapper ou a ação, não ambos
      - name: Upload and Scan - Wrapper
        run: |
          curl -L -o veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/24.7.14.0/vosp-api-wrappers-java-24.7.14.0.jar
          java -jar veracode-wrapper.jar -vid "${{ secrets.VERACODE_ID }}" -vkey "${{ secrets.VERACODE_KEY }}" -action UploadAndScan -deleteincompletescan 2 -createprofile true -appname "Verademo-python-1" -version "${{ github.run_id }}" -filepath "./${{env.package_path}}/${{env.package_name}}"
        
      # Ou, se preferir usar a ação do GitHub, remova a etapa do wrapper e use somente a ação
      - name: Upload and Scan - Action
        uses: veracode/veracode-uploadandscan-action@0.2.7
        with:
          appname: "Verademo-python-1"
          filepath: "./${{env.package_path}}/${{env.package_name}}"
          vid: "${{ secrets.VERACODE_ID }}"
          vkey: "${{ secrets.VERACODE_KEY }}"
          deleteincompletescan: 2

  Veracode-Sandbox-Scan:
    if: github.ref == 'refs/heads/sandbox-scan'
    name: Veracode Sandbox Scan
    runs-on: ubuntu-latest
    needs: [veracode-auto-package]
    strategy:
      fail-fast: true
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artfacts
          path: ./${{env.package_path}}

      - name: Upload and Scan
        run: |
          curl -L -o veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/24.7.14.0/vosp-api-wrappers-java-24.7.14.0.jar
          java -jar veracode-wrapper.jar -vid "${{ secrets.VERACODE_ID }}" -vkey "${{ secrets.VERACODE_KEY }}" -action UploadAndScan -deleteincompletescan 2 -createprofile true -appname "Verademo-python-1" -version "${{ github.run_id }}" -filepath "./${{env.package_path}}/${{env.package_name}}" -createsandbox true -sandboxname "${{ github.ref }}"

      # Ou, use a ação, mas remova a etapa do wrapper
      - name: Upload and Scan - Action
        uses: veracode/veracode-uploadandscan-action@0.2.7
        with:
          appname: "Verademo-python-1"
          filepath: "./${{env.package_path}}/${{env.package_name}}"
          vid: "${{ secrets.VERACODE_ID }}"
          vkey: "${{ secrets.VERACODE_KEY }}"
          deleteincompletescan: 2
