
on: 
  push: 
    branches: [master]

jobs:
  veracode-auto-package:
    name: Veracode Auto Package
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Veracode CLI Download and Package
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output veracode-auto-pack-Web-dotnet-js.zip --trust
          ls -l
          
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: veracode_pack
          path: veracode-auto-pack-Web-dotnet-js.zip
