on: 
  push: 
    branches: [master]

jobs:
  veracode-auto-package:
    name: Veracode Auto Package
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Veracode CLI Download and Package
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output veracode-auto-pack-Web-dotnet-js.zip --trust
          ls -l

      - name: Pipeline Scan with wrapper - default policy
        env:
          POLICY_NAME: Veracode Recommended Medium
        run: |
          curl -O -L https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -u pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar -vid "${{ secrets.VID }}" -vkey "${{ secrets.VKEY }}" --file "./${{env.package_path}}/${{env.package_name}}" -pn "${{ env.POLICY_NAME }}" --issue_details true --json_output true
        continue-on-error: true


  Veracode-Policy-Scan:
# esse job possui diversas formas de executar o upload and scan, com o Java Wrapper ou Action.
# escolha a que melhor se ajustar ao ambiente
    name: Veracode Policy Scan
    runs-on: ubuntu-latest
    needs: [veracode-auto-package]

    steps:
     - name: Download artfacts
       uses: actions/download-artifact@v4
       with:
          name: artfacts
          path: ./${{env.package_path}}

     - name: Upload and Scan
       env:
        APPLICATION_NAME: Verademo-python-1
        run: |
          curl -L -o veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/24.7.14.0/vosp-api-wrappers-java-24.7.14.0.jar
          java -jar veracode-wrapper.jar -vid "${{ secrets.VID }}" -vkey "${{ secrets.VKEY }}" -action UploadAndScan -deleteincompletescan 2 -createprofile true -appname "${{ env.APPLICATION_NAME }}" -version "${{ github.run_id }}" -filepath "./${{env.package_path}}/${{env.package_name}}"

     - name: Upload and Scan - Action
       uses: veracode/veracode-uploadandscan-action@0.2.7
       with:
          appname: "Verademo-python-1"
          filepath: "./${{env.package_path}}/${{env.package_name}}"
          vid: "${{ secrets.VID }}"
          vkey: "${{ secrets.VKEY }}"
          deleteincompletescan: 2

  Veracode-Sandbox-Scan:
# esse job possui diversas formas de executar o upload and scan, com o Java Wrapper ou Action.
# escolha a que melhor se ajustar ao ambiente
    if: github.ref == 'refs/heads/sandbox-scan'
    name: Veracode Sandbox Scan
    runs-on: ubuntu-latest
    needs: [veracode-auto-package]
    strategy:
      fail-fast: true
    env:
      APPLICATION_NAME: Verademo-python-1

    steps:
      - name: Download artfacts
        uses: actions/download-artifact@v4
        with:
          name: artfacts
          path: ./${{env.package_path}}

      - name: Upload and Scan
        run: |
          curl -L -o veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/24.7.14.0/vosp-api-wrappers-java-24.7.14.0.jar
          java -jar veracode-wrapper.jar -vid "${{ secrets.VID }}" -vkey "${{ secrets.VKEY }}" -action UploadAndScan -deleteincompletescan 2 -createprofile true -appname "${{ env.APPLICATION_NAME }}" -version "${{ github.run_id }}" -filepath "./${{env.package_path}}/${{env.package_name}}" -createsandbox true -sandboxname "${{ github.ref }}" 

      - name: Upload and Scan - Action
        uses: veracode/veracode-uploadandscan-action@0.2.7
        with:
          appname: "Verademo-python-1"
          filepath: "./${{env.package_path}}/${{env.package_name}}"
          vid: "${{ secrets.VID }}"
          vkey: "${{ secrets.VKEY }}"
          deleteincompletescan: 2
